# Generated by Django 5.0.1 on 2024-01-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0003_record_qaytarish_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutubxonachi',
            name='ish_vaqti',
            field=models.CharField(choices=[('8 dan 17 gacha', '8 dan 17 gacha'), ('18 dan 7 gacha', '18 dan 7 gacha')], max_length=30),
        ),
    ]
